config/routes.rb
Rails.application.routes.draw do
  post 'cart/place_order', to: 'carts#place_order', as: :place_order


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  post 'update_cart_address', to: 'carts#update_cart_address', as: :update_cart_address


  post '/process_checkout', to: 'carts#process_checkout', as: :process_checkout_cart


  get 'checkout', to: 'carts#checkout', as: :checkout
  resources :orders, only: :create

  put '/carts/update_quantity', to: 'carts#update_quantity', as: :update_quantity_carts





  post 'add_to_cart', to: 'carts#add_to_cart', as: :add_to_cart
  get 'show_cart', to: 'carts#show_cart', as: :show_cart
  devise_for :users

  resources :carts, only: [] do
    post 'process_checkout', on: :collection
    post 'checkout', on: :collection
    get 'checkout', on: :member
    get :show_cart, on: :collection
    post :update_quantity, on: :collection
    collection do
      delete 'remove_from_cart'
    end
  end

  resources :products do
   get :search, on: :collection
    collection do
      get 'on_sale'
      get 'new_products'
      get 'recently_updated_products'
    end
  end

  resources :categories do
    resources :products
  end
  resources :products, only: [:new, :create]
  resources :categories, only: [:new, :create, :show]
  get 'home/about'
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end

  def about; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Crick Sports', root_path, class:"nav-link"%>
        </li>
      </ul>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link"%>
        </li>
      </ul>
      <div class="collapse navbar-collapse" >

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
  <%= link_to 'Product', products_path, class:"nav-link" %>
  <li class="nav-item">
   <li class="nav-item">
        <%= link_to 'Categories', categories_path, class: 'nav-link' %>
      </li>
      </ul>
  </div>

</nav>

app/views/home/about.html.erb
<div class="container mt-4">
  <h1>About Us...</h1>
  <p>Welcome to our online store! At Crick Sports, we are dedicated to providing high-quality cricket products to enthusiasts and athletes of all levels.</p>
  <p>Our mission is to offer a wide range of cricket gear, clothing, accessories, and equipment that cater to your cricket needs. Whether you're a professional player or a passionate fan, we have something for everyone.</p>
  <p>With a commitment to quality and customer satisfaction, we strive to ensure that our products meet the highest standards. Our team of experts is passionate about cricket and is here to assist you in finding the perfect gear that suits your style and preferences.</p>
  <p>Thank you for choosing Crick Sports as your cricket equipment provider. We look forward to serving you and helping you enjoy the game to the fullest!</p>
</div>

app/views/home/categories.html.erb
<h1>Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

app/views/home/index.html.erb
<!-- app/views/home.html.erb -->

<div id="hero" class="jumbotron jumbotron-fluid text-center bg-primary text-white">
  <div class="container">
    <h1 class="display-4">Crick Sports</h1>
    <p class="lead">Welcome to our online store</p>
    <p>We specialize in cricket products for all enthusiasts!</p>
    <a href="<%= products_path %>" class="btn btn-light btn-lg">Shop Now</a>
  </div>
</div>

<div id="about" class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2>Our Products</h2>
      <p>Explore our collection of high-quality cricket gear, clothing, accessories, and equipment. We offer the latest trends and technologies to enhance your cricket experience.</p>
    </div>
  </div>
</div>