config/routes.rb
Rails.application.routes.draw do
  post 'cart/place_order', to: 'carts#place_order', as: :place_order


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  post 'update_cart_address', to: 'carts#update_cart_address', as: :update_cart_address


  post '/process_checkout', to: 'carts#process_checkout', as: :process_checkout_cart


  get 'checkout', to: 'carts#checkout', as: :checkout
  resources :orders, only: :create

  put '/carts/update_quantity', to: 'carts#update_quantity', as: :update_quantity_carts





  post 'add_to_cart', to: 'carts#add_to_cart', as: :add_to_cart
  get 'show_cart', to: 'carts#show_cart', as: :show_cart
  devise_for :users

  resources :carts, only: [] do
    post 'process_checkout', on: :collection
    post 'checkout', on: :collection
    get 'checkout', on: :member
    get :show_cart, on: :collection
    post :update_quantity, on: :collection
    collection do
      delete 'remove_from_cart'
    end
  end

  resources :products do
   get :search, on: :collection
    collection do
      get 'on_sale'
      get 'new_products'
      get 'recently_updated_products'
    end
  end

  resources :categories do
    resources :products
  end
  resources :products, only: [:new, :create]
  resources :categories, only: [:new, :create, :show]
  get 'home/about'
  root 'home#index'

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items

  def remove_product(product_id)
    item = items.find { |item| item["product_id"] == product_id }
    items.delete(item) if item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def place_order

    # Retrieve address data from the session

    if user_signed_in?

      Address.create!(

        address: session[:address],

        postal: session[:postal],

        province: session[:province],

        user_id: current_user.id

      )

    end



    # Clear other relevant session data (e.g., cart)

    session.delete(:cart)

    session.delete(:address) # Optional: Clear the address from the session





    redirect_to products_path, notice: "Order placed successfully!"

  end
  GST = 5

  State_tax = {

    "Alberta"                   => 0,

    "British Columbia"          => 7,

    "Manitoba"                  => 7,

    "New Brunswick"             => 10,

    "Newfoundland and Labrador" => 10,

    "Northwest Territories"     => 0,

    "Nova Scotia"               => 10,

    "Nunavut"                   => 0,

    "Ontario"                   => 8,

    "Prince Edward Island"      => 10,

    "Quebec"                    => 9.975,

    "Saskatchewan"              => 6,

    "Yukon"                     => 0

  }

  def update_cart_address
    @address = params[:address]

    @postal_code = params[:postal_code]

    @province = params[:province]



    session[:address] = @address

    session[:postal_code] = @postal_code

    session[:province] = @province




    redirect_to root_path
  end

  def show_cart
    @cart_items = cart_items
  end

  def add_to_cart
    product_id = params[:product_id].to_i
    cart_items[product_id] ||= 0
    cart_items[product_id] += 1
    puts "Cart after adding item: #{session[:cart]}"
    redirect_to show_cart_path
  end

  def update_quantity
    product_id = params[:product_id].to_i
    quantity = params[:quantity].to_i
    if quantity <= 0
      cart_items.delete(product_id)
    else
      cart_items[product_id] = quantity
    end
    redirect_to show_cart_path
  end

  def remove_from_cart
    product_id = params[:product_id].to_i
    cart_items.delete(product_id)
    session[:cart] = cart_items
    puts "Updated cart items: #{cart_items}"

    redirect_to show_cart_path
  end

  def checkout
    @cart_items = cart_items
    @cart_contents = session[:cart] || {}

    @address = session[:address]

    @postal_code = session[:postal_code]

    @province = session[:province]

    # Call the method on the order instance
  end

  private

  def calculate_totals
    @order.total_price = 0
    @cart_items.each do |product_id, quantity|
      product = Product.find(product_id)
      @order.total_price += product.product_price * quantity
    end
  end

  def cart_items
    session[:cart] ||= {}
    session[:cart]
  end

  def process_checkout
    @cart_items = cart_items
    @order = current_user.orders.build(order_params)
    @order.calculate_taxes

    if @order.save
      @cart_items.each do |product_id, quantity|
        # Deduct quantity from product inventory
        product = Product.find(product_id)
        product.update(inventory: product.inventory - quantity)
      end

      session[:cart] = {} # Clear the cart
      redirect_to order_confirmation_path(@order)
    else
      render :checkout
    end
  end

  def order_params
    params.require(:order).permit(:address, :province)
  end

  def check_out
    @cart_contents = session[:cart] || {}

    @address = session[:address]

    @postal_code = session[:postal_code]

    @province = session[:province]
  end

  def checkout_params
    params.require(:checkout).permit(:address, :postal_code, :province)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_address_form.html.erb
<%= form_tag update_cart_address_path, method: :post do %>

  <%= label_tag :address, "Address" %>

  <%= text_field_tag :address, @address %>



  <%= label_tag :postal_code, "Postal Code" %>

  <%= text_field_tag :postal_code, @postal_code %>



  <%= label_tag :province, "Province" %>

  <%= select_tag :province, options_for_select(["Newfoundland and Labrador", "Nova Scotia", "Prince Edward Island", "New Brunswick", "Ontario", "Quebec", "Manitoba", "Saskatchewan", "Alberta", "British Columbia"]), selected: @province %>



  <%= submit_tag "Update Address" %>

  <% end %>

app/views/carts/checkout.html.erb
<% if @cart_items.present? %>
  <table class="table">
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
    <% total_price = 0%>
      <% @cart_items.each do |product_id, quantity| %>
        <% product = Product.find(product_id) %>
        <tr>
          <td><%= product.product_name %></td>
          <td><%= quantity %></td>
          <td><%= number_to_currency(product.product_price * quantity) %></td>
          <% total_price += product.product_price * quantity %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% if @address.present? %>
    <!-- Display shipping information -->
  GST: <%= number_to_currency(CartsController::GST * total_price /100 )%>

  <br>



    HST/PST: <%= number_to_currency(CartsController::State_tax[@province] *total_price / 100)%>



  <br>

  <br>

  Total: <%=  number_to_currency(total_price +CartsController::State_tax[@province] *total_price / 100 + CartsController::GST * total_price /100 ) %>

  </div>

    <div class="container">
      <h3>Shipping Address</h3>
      <p><strong>Address:</strong> <%= @address %></p>
      <p><strong>Postal Code:</strong> <%= @postal_code %></p>
      <p><strong>Province:</strong> <%= @province %></p>

      <!-- Place Order button -->
    </div>

    <%= form_tag place_order_path, method: :post do %>

    <%= submit_tag "Place Order" %>

  <% end %>
  <% else %>
    <%= render "address_form" %>
  <% end %>

<% end %>

app/views/carts/show_cart.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>


<div class="container">
  <h1>Your Shopping Cart</h1>

  <% if @cart_items.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Product</th>
          <th>Quantity</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |product_id, quantity| %>
          <tr>
            <td><%= Product.find(product_id).product_name %></td>
            <td>
              <%= form_tag update_quantity_carts_path, method: :put do %>
                <%= hidden_field_tag :product_id, product_id %>
                <%= number_field_tag :quantity, quantity, class: 'form-control', min: 1 %>
                <%= submit_tag 'Update', class: 'btn btn-primary btn-sm' %>
              <% end %>
            </td>
            <td>
  <%= button_to 'Remove', remove_from_cart_carts_path(product_id: product_id),
              method: :delete %>
</td>

          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="text-right">
      <%= link_to 'Continue Shopping', products_path, class: 'btn btn-secondary' %>
      <%= link_to 'Checkout', checkout_path, class: 'btn btn-primary' %>

    </div>
  <% else %>
    <p>Your shopping cart is empty.</p>
  <% end %>
</div>
</body>