config/routes.rb
Rails.application.routes.draw do
  post 'cart/place_order', to: 'carts#place_order', as: :place_order


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  post 'update_cart_address', to: 'carts#update_cart_address', as: :update_cart_address


  post '/process_checkout', to: 'carts#process_checkout', as: :process_checkout_cart


  get 'checkout', to: 'carts#checkout', as: :checkout
  resources :orders, only: :create

  put '/carts/update_quantity', to: 'carts#update_quantity', as: :update_quantity_carts





  post 'add_to_cart', to: 'carts#add_to_cart', as: :add_to_cart
  get 'show_cart', to: 'carts#show_cart', as: :show_cart
  devise_for :users

  resources :carts, only: [] do
    post 'process_checkout', on: :collection
    post 'checkout', on: :collection
    get 'checkout', on: :member
    get :show_cart, on: :collection
    post :update_quantity, on: :collection
    collection do
      delete 'remove_from_cart'
    end
  end

  resources :products do
   get :search, on: :collection
    collection do
      get 'on_sale'
      get 'new_products'
      get 'recently_updated_products'
    end
  end

  resources :categories do
    resources :products
  end
  resources :products, only: [:new, :create]
  resources :categories, only: [:new, :create, :show]
  get 'home/about'
  root 'home#index'

end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="styles.css">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <div class="py-3">
      <% if user_signed_in? %>
        <p class="mb-0">Signed in as: <%= current_user.email %></p>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "btn btn-danger" %>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary me-2" %>
        <%= link_to 'Log in', new_user_session_path, class: "btn btn-secondary" %>
      <% end %>
      <div id="cart-link" class="mt-3">
        <%= link_to 'Shopping Cart', show_cart_path, class: "btn btn-info" %>
      </div>
    </div>

    <%= render 'home/header' %>

    <div class="mt-5">
      <%= yield %>
    </div>
  </div>
</body>
</html>